config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :videocards
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  #has_many :products, as: :productable
  validates :name, presence: { message: "deverá ser especificado." }

app/models/product.rb
class Product < ApplicationRecord
  #belongs_to :productable, :polymorphic => true

  has_one :videocard, dependent: :destroy
  #has_many :prices, through: :stores (verificar se é possível estabelecer uma relação many to many concomitante com a relação polimórfica, ou se mesmo a relação com o preço e a loja tem que se valer da polimórfica)

  validates :platform, presence: { message: "deverá ser especificada." }
  validates :name, presence: { message: "deverá ser especificado." }

  validates_associated :videocard

end

app/models/videocard.rb
class Videocard < ApplicationRecord
  belongs_to :product

  validates :tdp, presence: { message: "deverá ser especificado." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :image, :type, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :partnum, :manufacturer, :platform)
    end
end

app/controllers/videocards_controller.rb
class VideocardsController < ApplicationController
  before_action :set_videocard, only: [:show, :edit, :update, :destroy]

  # GET /videocards
  # GET /videocards.json
  def index
    @videocards = Videocard.all
  end

  # GET /videocards/1
  # GET /videocards/1.json
  def show
  end

  # GET /videocards/new
  def new
    @videocard = Videocard.new
  end

  # GET /videocards/1/edit
  def edit
  end

  # POST /videocards
  # POST /videocards.json
  def create
    @videocard = Videocard.new(videocard_params)

    respond_to do |format|
      if @videocard.save
        format.html { redirect_to @videocard, notice: 'Videocard was successfully created.' }
        format.json { render :show, status: :created, location: @videocard }
      else
        format.html { render :new }
        format.json { render json: @videocard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videocards/1
  # PATCH/PUT /videocards/1.json
  def update
    respond_to do |format|
      if @videocard.update(videocard_params)
        format.html { redirect_to @videocard, notice: 'Videocard was successfully updated.' }
        format.json { render :show, status: :ok, location: @videocard }
      else
        format.html { render :edit }
        format.json { render json: @videocard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videocards/1
  # DELETE /videocards/1.json
  def destroy
    @videocard.destroy
    respond_to do |format|
      format.html { redirect_to videocards_url, notice: 'Videocard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videocard
      @videocard = Videocard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videocard_params
      params.require(:videocard).permit(:memory, :memorytype, :memoryinterfacewidth, :memorybaseclock, :memoryboostclock, :memorybandwidth, :computingpower, :interface, :chipset, :sli, :slitype, :crossfire, :crossfiretype, :dviport, :hdmiport, :minihdmiport, :displayport, :minidisplayport, :expansionslotw, :tdp, :maxtemp, :powerconnectors, :framesync, :ventoinha, :maximumresolution, :multimonitor, :comprimento, :largura, :altura, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/videocards_helper.rb
module VideocardsHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Type</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.image %></td>
        <td><%= category.type %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @category.image %>
</p>

<p>
  <strong>Type:</strong>
  <%= @category.type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/headers/_form.html.erb
<%= form_for(header) do |f| %>
  <% if header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(header.errors.count, "error") %> prohibited this header from being saved:</h2>

      <ul>
      <% header.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :partnum %>
    <%= f.text_field :partnum %>
  </div>

  <div class="field">
    <%= f.label :creator %>
    <%= f.text_field :creator %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :platform %>
    <%= f.text_field :platform %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Monte seu PC!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Nome do Produto' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image, 'Link da Imagem' %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :partnum, 'Número de Registro da Parte (Part Number)' %>
    <%= f.text_field :partnum %>
  </div>

  <div class="field">
    <%= f.label :manufacturer, 'Fabricante' %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :platform, 'Plataforma' %>
    <%= f.text_field :platform %>
  </div>

  <div class="actions">
    <%= f.submit 'Adicionar Produto' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Partnum</th>
      <th>Manufacturer</th>
      <th>Platform</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= image_tag product.image %></td>
        <td><%= product.partnum %></td>
        <td><%= product.manufacturer %></td>
        <td><%= product.platform %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Voltar', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image %>
</p>

<p>
  <strong>Partnum:</strong>
  <%= @product.partnum %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @product.manufacturer %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @product.platform %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/videocards/_form.html.erb
<%= form_for(videocard) do |f| %>
  <% if videocard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(videocard.errors.count, "error") %> prohibited this videocard from being saved:</h2>

      <ul>
      <% videocard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :memory %>
    <%= f.number_field :memory %>
  </div>

  <div class="field">
    <%= f.label :memorytype %>
    <%= f.text_field :memorytype %>
  </div>

  <div class="field">
    <%= f.label :memoryinterfacewidth %>
    <%= f.number_field :memoryinterfacewidth %>
  </div>

  <div class="field">
    <%= f.label :memorybaseclock %>
    <%= f.number_field :memorybaseclock %>
  </div>

  <div class="field">
    <%= f.label :memoryboostclock %>
    <%= f.number_field :memoryboostclock %>
  </div>

  <div class="field">
    <%= f.label :memorybandwidth %>
    <%= f.number_field :memorybandwidth %>
  </div>

  <div class="field">
    <%= f.label :computingpower %>
    <%= f.text_field :computingpower %>
  </div>

  <div class="field">
    <%= f.label :interface %>
    <%= f.text_field :interface %>
  </div>

  <div class="field">
    <%= f.label :chipset %>
    <%= f.text_field :chipset %>
  </div>

  <div class="field">
    <%= f.label :sli %>
    <%= f.check_box :sli %>
  </div>

  <div class="field">
    <%= f.label :slitype %>
    <%= f.text_field :slitype %>
  </div>

  <div class="field">
    <%= f.label :crossfire %>
    <%= f.check_box :crossfire %>
  </div>

  <div class="field">
    <%= f.label :crossfiretype %>
    <%= f.text_field :crossfiretype %>
  </div>

  <div class="field">
    <%= f.label :dviport %>
    <%= f.number_field :dviport %>
  </div>

  <div class="field">
    <%= f.label :hdmiport %>
    <%= f.number_field :hdmiport %>
  </div>

  <div class="field">
    <%= f.label :minihdmiport %>
    <%= f.number_field :minihdmiport %>
  </div>

  <div class="field">
    <%= f.label :displayport %>
    <%= f.number_field :displayport %>
  </div>

  <div class="field">
    <%= f.label :minidisplayport %>
    <%= f.number_field :minidisplayport %>
  </div>

  <div class="field">
    <%= f.label :expansionslotw %>
    <%= f.number_field :expansionslotw %>
  </div>

  <div class="field">
    <%= f.label :tdp %>
    <%= f.number_field :tdp %>
  </div>

  <div class="field">
    <%= f.label :maxtemp %>
    <%= f.text_field :maxtemp %>
  </div>

  <div class="field">
    <%= f.label :powerconnectors %>
    <%= f.text_field :powerconnectors %>
  </div>

  <div class="field">
    <%= f.label :framesync %>
    <%= f.text_field :framesync %>
  </div>

  <div class="field">
    <%= f.label :ventoinha %>
    <%= f.check_box :ventoinha %>
  </div>

  <div class="field">
    <%= f.label :maximumresolution %>
    <%= f.text_field :maximumresolution %>
  </div>

  <div class="field">
    <%= f.label :multimonitor %>
    <%= f.check_box :multimonitor %>
  </div>

  <div class="field">
    <%= f.label :comprimento %>
    <%= f.number_field :comprimento %>
  </div>

  <div class="field">
    <%= f.label :largura %>
    <%= f.number_field :largura %>
  </div>

  <div class="field">
    <%= f.label :altura %>
    <%= f.number_field :altura %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videocards/edit.html.erb
<h1>Editing Videocard</h1>

<%= render 'form', videocard: @videocard %>

<%= link_to 'Show', @videocard %> |
<%= link_to 'Back', videocards_path %>

app/views/videocards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videocards</h1>

<table>
  <thead>
    <tr>
      <th>Memory</th>
      <th>Memorytype</th>
      <th>Memoryinterfacewidth</th>
      <th>Memorybaseclock</th>
      <th>Memoryboostclock</th>
      <th>Memorybandwidth</th>
      <th>Computingpower</th>
      <th>Interface</th>
      <th>Chipset</th>
      <th>Sli</th>
      <th>Slitype</th>
      <th>Crossfire</th>
      <th>Crossfiretype</th>
      <th>Dviport</th>
      <th>Hdmiport</th>
      <th>Minihdmiport</th>
      <th>Displayport</th>
      <th>Minidisplayport</th>
      <th>Expansionslotw</th>
      <th>Tdp</th>
      <th>Maxtemp</th>
      <th>Powerconnectors</th>
      <th>Framesync</th>
      <th>Ventoinha</th>
      <th>Maximumresolution</th>
      <th>Multimonitor</th>
      <th>Comprimento</th>
      <th>Largura</th>
      <th>Altura</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videocards.each do |videocard| %>
      <tr>
        <td><%= videocard.memory %></td>
        <td><%= videocard.memorytype %></td>
        <td><%= videocard.memoryinterfacewidth %></td>
        <td><%= videocard.memorybaseclock %></td>
        <td><%= videocard.memoryboostclock %></td>
        <td><%= videocard.memorybandwidth %></td>
        <td><%= videocard.computingpower %></td>
        <td><%= videocard.interface %></td>
        <td><%= videocard.chipset %></td>
        <td><%= videocard.sli %></td>
        <td><%= videocard.slitype %></td>
        <td><%= videocard.crossfire %></td>
        <td><%= videocard.crossfiretype %></td>
        <td><%= videocard.dviport %></td>
        <td><%= videocard.hdmiport %></td>
        <td><%= videocard.minihdmiport %></td>
        <td><%= videocard.displayport %></td>
        <td><%= videocard.minidisplayport %></td>
        <td><%= videocard.expansionslotw %></td>
        <td><%= videocard.tdp %></td>
        <td><%= videocard.maxtemp %></td>
        <td><%= videocard.powerconnectors %></td>
        <td><%= videocard.framesync %></td>
        <td><%= videocard.ventoinha %></td>
        <td><%= videocard.maximumresolution %></td>
        <td><%= videocard.multimonitor %></td>
        <td><%= videocard.comprimento %></td>
        <td><%= videocard.largura %></td>
        <td><%= videocard.altura %></td>
        <td><%= videocard.color %></td>
        <td><%= link_to 'Show', videocard %></td>
        <td><%= link_to 'Edit', edit_videocard_path(videocard) %></td>
        <td><%= link_to 'Destroy', videocard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videocard', new_videocard_path %>

app/views/videocards/new.html.erb
<h1>New Videocard</h1>

<%= render 'form', videocard: @videocard %>

<%= link_to 'Back', videocards_path %>

app/views/videocards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Memory:</strong>
  <%= @videocard.memory %>
</p>

<p>
  <strong>Memorytype:</strong>
  <%= @videocard.memorytype %>
</p>

<p>
  <strong>Memoryinterfacewidth:</strong>
  <%= @videocard.memoryinterfacewidth %>
</p>

<p>
  <strong>Memorybaseclock:</strong>
  <%= @videocard.memorybaseclock %>
</p>

<p>
  <strong>Memoryboostclock:</strong>
  <%= @videocard.memoryboostclock %>
</p>

<p>
  <strong>Memorybandwidth:</strong>
  <%= @videocard.memorybandwidth %>
</p>

<p>
  <strong>Computingpower:</strong>
  <%= @videocard.computingpower %>
</p>

<p>
  <strong>Interface:</strong>
  <%= @videocard.interface %>
</p>

<p>
  <strong>Chipset:</strong>
  <%= @videocard.chipset %>
</p>

<p>
  <strong>Sli:</strong>
  <%= @videocard.sli %>
</p>

<p>
  <strong>Slitype:</strong>
  <%= @videocard.slitype %>
</p>

<p>
  <strong>Crossfire:</strong>
  <%= @videocard.crossfire %>
</p>

<p>
  <strong>Crossfiretype:</strong>
  <%= @videocard.crossfiretype %>
</p>

<p>
  <strong>Dviport:</strong>
  <%= @videocard.dviport %>
</p>

<p>
  <strong>Hdmiport:</strong>
  <%= @videocard.hdmiport %>
</p>

<p>
  <strong>Minihdmiport:</strong>
  <%= @videocard.minihdmiport %>
</p>

<p>
  <strong>Displayport:</strong>
  <%= @videocard.displayport %>
</p>

<p>
  <strong>Minidisplayport:</strong>
  <%= @videocard.minidisplayport %>
</p>

<p>
  <strong>Expansionslotw:</strong>
  <%= @videocard.expansionslotw %>
</p>

<p>
  <strong>Tdp:</strong>
  <%= @videocard.tdp %>
</p>

<p>
  <strong>Maxtemp:</strong>
  <%= @videocard.maxtemp %>
</p>

<p>
  <strong>Powerconnectors:</strong>
  <%= @videocard.powerconnectors %>
</p>

<p>
  <strong>Framesync:</strong>
  <%= @videocard.framesync %>
</p>

<p>
  <strong>Ventoinha:</strong>
  <%= @videocard.ventoinha %>
</p>

<p>
  <strong>Maximumresolution:</strong>
  <%= @videocard.maximumresolution %>
</p>

<p>
  <strong>Multimonitor:</strong>
  <%= @videocard.multimonitor %>
</p>

<p>
  <strong>Comprimento:</strong>
  <%= @videocard.comprimento %>
</p>

<p>
  <strong>Largura:</strong>
  <%= @videocard.largura %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @videocard.altura %>
</p>

<p>
  <strong>Color:</strong>
  <%= @videocard.color %>
</p>

<%= link_to 'Edit', edit_videocard_path(@videocard) %> |
<%= link_to 'Back', videocards_path %>